# This workflow is used to test a template with a larger disk usage, which will take longer to pull to the host
name: 'm1-6c14-40gb-1'
on:
  workflow_dispatch:

jobs:
  m1-6c14-40gb-1:
    runs-on: [ 
      "${{ github.run_id }}-${{ strategy.job-index }}",
      "anka-template:84266873-da90-4e0d-903b-ed0233471f9f", 
      "anka-template-tag:6c14r-40gb",
    ]
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -laht
          sw_vers
          hostname
          echo "123"
          sysctl -n hw.ncpu
      - run: whoami
