name: 't1-with-tag-1-failure'
on:
  workflow_dispatch:

jobs:
  testJob:
    runs-on: [ 
      "self-hosted", 
      "anka", 
      "anka-template:c092c6f6-198c-470f-9526-9c998efe7ab5", 
      "anka-template-tag:vanilla+port-forward-22+brew-git",
      "run-id:${{ github.run_id }}", 
      "unique-id:1"
    ]
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "hello"