name: 't2-3c6r-1-90s-pause'
on:
  workflow_dispatch:

jobs:
  t2-3c6r-1-90s-pause:
    runs-on: [ 
      "${{ github.run_id }}-${{ strategy.job-index }}",
      "anka-template:84266873-da90-4e0d-903b-ed0233471f9f", 
      "anka-template-tag:3c6r",
    ]
    steps:
      - uses: actions/checkout@v3
      - run: |
          ls -laht
          sw_vers
          hostname
          echo "123"
          sysctl -n hw.ncpu
          sleep 90
      - run: whoami
